#!/usr/bin/env python3
"""Stage B: lens sanity gate. Loads the model + lens, runs the three checks from the
brief on generic calibration text, writes a report, and refuses (nonzero exit) if check 1
(identity collapse at the last fitted layer) fails.

Usage:
    python scripts/run_gate.py config/smoke.qwen3.5-0.8b.yaml

Requires scripts/download_artifacts.py to have been run against the same config first.
"""

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _bootstrap  # noqa: F401

from typo_readout.config import Config, REPO_ROOT
from typo_readout.gate import run_gate, render_markdown
from typo_readout.lens_io import load_lens
from typo_readout.model_io import load_model
from typo_readout.provenance import write_provenance, ArtifactRecord


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", help="path to a config/*.yaml file")
    args = parser.parse_args()

    config = Config.load(args.config)
    print(f"[gate] config: {args.config} (tier={config.run.tier})")

    print(f"[gate] loading lens: {config.lens.repo}/{config.lens.filename}")
    lens = load_lens(config.lens)
    print(f"[gate] lens: {lens!r}")

    print(f"[gate] loading model: {config.model.hf_repo} (dtype={config.model.dtype})")
    loaded = load_model(config.model)
    print(
        f"[gate] model loaded via {loaded.auto_class_used} on device={loaded.device}, "
        f"n_layers={loaded.lens_model.n_layers}, d_model={loaded.lens_model.d_model}, "
        f"layout={loaded.lens_model.layout}"
    )

    print(f"[gate] running checks on {config.model.hf_repo} ...")
    report = run_gate(
        lens, loaded.lens_model, config.gate, model_repo=config.model.hf_repo
    )

    md = render_markdown(report)
    print("\n" + md)

    run_dir = REPO_ROOT / "runs" / f"gate-{config.run.tier}"
    run_dir.mkdir(parents=True, exist_ok=True)
    json_path = run_dir / "gate_report.json"
    md_path = run_dir / "gate_report.md"
    import json

    json_path.write_text(json.dumps(report.to_dict(), indent=2))
    md_path.write_text(md)
    print(f"[gate] wrote {json_path} and {md_path}")

    provenance_path = write_provenance(
        config=config,
        stage="gate",
        artifacts=[
            ArtifactRecord.from_file(json_path, source="generated by scripts/run_gate.py"),
        ],
        extra={
            "gate_auto_class_used": loaded.auto_class_used,
            "gate_device": loaded.device,
            "gate_overall_pass": report.overall_pass,
            "gate_report_path": str(json_path.relative_to(REPO_ROOT)),
        },
    )
    print(f"[gate] wrote {provenance_path} (and repo-root provenance.json)")

    if not report.overall_pass:
        print(
            "\n[gate] REFUSING to proceed: check 1 (identity collapse at the last fitted "
            "layer) failed. Fix the lens/model pairing before running the eval.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("\n[gate] check 1 passed. Safe to proceed to Stage C.")


if __name__ == "__main__":
    main()
