#!/usr/bin/env python3
"""Stage C: behavioral pre-check. For each (subset of) bank item, checks whether the
subject model recovers the misspelling's corrected word via a direct, chat-templated,
enable_thinking=False question -- independent of the lens. Persists pass/fail per item
and reports the retention rate.

Usage:
    python scripts/run_behavioral.py config/smoke.qwen3.5-0.8b.yaml

Requires scripts/download_artifacts.py and scripts/run_gate.py (check 1 passing) to have
been run against the same config first.
"""

import argparse
import dataclasses
import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _bootstrap  # noqa: F401

from typo_readout.bank_io import load_items, bank_artifact_record
from typo_readout.behavioral import run_stage_c, retention_rate, render_markdown
from typo_readout.config import Config, REPO_ROOT
from typo_readout.model_io import load_model
from typo_readout.provenance import write_provenance, ArtifactRecord


def main() -> None:
    logging.basicConfig(level=logging.WARNING, format="[%(levelname)s] %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", help="path to a config/*.yaml file")
    args = parser.parse_args()

    config = Config.load(args.config)
    print(f"[behavioral] config: {args.config} (tier={config.run.tier})")

    if not config.stage_c.enabled:
        print("[behavioral] stage_c_behavioral.enabled=false in config -- nothing to do.")
        return

    all_items = load_items(config.bank)
    items = all_items if config.bank.n_items is None else all_items[: config.bank.n_items]
    print(
        f"[behavioral] bank family '{config.bank.family}': using {len(items)} of "
        f"{len(all_items)} frozen items (config.bank.n_items={config.bank.n_items!r}, "
        "first-N by file order)"
    )

    print(f"[behavioral] loading model: {config.model.hf_repo} (dtype={config.model.dtype})")
    loaded = load_model(config.model)
    print(f"[behavioral] model loaded via {loaded.auto_class_used} on device={loaded.device}")

    print(
        f"[behavioral] running {len(items)} items x (1 greedy + {config.stage_c.n_trials} "
        f"sampled @ temp={config.stage_c.temperature}) generations ..."
    )
    results = run_stage_c(loaded, items, config.stage_c)

    md = render_markdown(results, model_repo=config.model.hf_repo, cfg=config.stage_c)
    print("\n" + md)

    run_dir = REPO_ROOT / "runs" / f"behavioral-{config.run.tier}"
    run_dir.mkdir(parents=True, exist_ok=True)
    jsonl_path = run_dir / "behavioral_results.jsonl"
    md_path = run_dir / "behavioral_report.md"

    with jsonl_path.open("w") as f:
        for r in results:
            f.write(json.dumps(dataclasses.asdict(r)) + "\n")
    md_path.write_text(md)
    print(f"[behavioral] wrote {jsonl_path} and {md_path}")

    rate = retention_rate(results)
    provenance_path = write_provenance(
        config=config,
        stage="behavioral",
        artifacts=[
            bank_artifact_record(config.bank),
            ArtifactRecord.from_file(jsonl_path, source="generated by scripts/run_behavioral.py"),
        ],
        extra={
            "behavioral_n_items": len(items),
            "behavioral_retention_rate": rate,
            "behavioral_auto_class_used": loaded.auto_class_used,
            "behavioral_device": loaded.device,
            "behavioral_results_path": str(jsonl_path.relative_to(REPO_ROOT)),
        },
    )
    print(f"[behavioral] wrote {provenance_path} (and repo-root provenance.json)")
    print(f"\n[behavioral] retention rate: {rate:.1%} ({sum(r.stage_c_pass for r in results)}/{len(results)})")


if __name__ == "__main__":
    main()
